#!/sbin/runscript

depend() {
    need net
}

start() {
	ebegin "Starting hudson"
	start-stop-daemon --start --quiet --exec /usr/sbin/hudson \
                --background --chuid hudson:hudson \
                --pidfile /var/run/hudson.pid -m \
                -- ${HUDSON_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping hudson"
	start-stop-daemon --stop --quiet --exec /usr/sbin/hudson \
                --pid-file=/var/run/hudson.pid
	eend $?
}

restart() {
        ebegin "Restart hudson"
        svc_stop
        sleep 5
        svc_start
        eend $? "Failed to restart hudson"
}
