#!/sbin/runscript

depend() {
    need net
}

start() {
	ebegin "Starting selenium-hub"
	start-stop-daemon --start --quiet --exec /usr/sbin/selenium-hub \
                --background --chuid selenium:selenium \
                --pidfile /var/run/selenium-hub.pid -m
	eend $?
}

stop() {
	ebegin "Stopping selenium-hub"
	start-stop-daemon --stop --quiet --exec /usr/sbin/selenium-hub \
                --pid-file=/var/run/selenium-hub.pid
    if [ -e /var/run/selenium-hub.pid ] ; then
        eerror "selenium-hub didn't stop cleanly!"
        eerror "Issuing a kill -9 ..."
        kill -9 $(cat /var/run/selenium-hub.pid)
    fi
	eend $?
}
